# Application name
spring.application.name=ProfResumeBuilder
server.port=${PORT:8080}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ProfResumeBuilder

# Serve React build from resources/static
spring.web.resources.static-locations=classpath:/static/
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true

# File upload limit (for signature images)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.profresumebuilder=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
